version: '3.1'

# windows dev and volume config
# options for plugin or theme development
#- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
#- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development

services:
  mongo-dev-db:
    image:  mongo:7.0.4
    container_name: mongo_dev_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./initial_data/:/docker-entrypoint-initdb.d/
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: 
      # MONGO_INITDB_ROOT_PASSWORD:
    user: root
    restart: always