version: '3.1'

services:
  mongo-db:
    image:  mongo:7.0.4
    container_name: mongo_db
    networks:
      - useerdb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./initial_data/:/docker-entrypoint-initdb.d/
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: 
      # MONGO_INITDB_ROOT_PASSWORD:
    user: root
    restart: always

  riddle:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - useerdb
    ports:
      - "3000:3000"
    command: npm run start
    restart: always

volumes:
  minio_data:
    driver: local
networks:
  useerdb:
    driver: bridge